### ISSUE TITLE
Issue with update on 5.4 

### ISSUE THREAD

**Issue by Spriingy** [Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin#7]
impossible to update OBS on the last version of Loupedeck. 
![image](https://user-images.githubusercontent.com/114013548/206842773-3dcaacdf-8e00-487c-8b09-484e048252f5.png)
[Loupedeck-Logs-20221210T093342 (1).zip](https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/files/10199585/Loupedeck-Logs-20221210T093342.1.zip)

**Comment by laperie** [comment]
The error is happening because for some reason Loupedeck installed cannot extract metadata from the installation package.
While the root cause  is still being investigated, a workaround to install the plugin manually:

1. Stop Loupedeck Service
2. Download the latest release from [  Plugin Releases ]( https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/releases )
3. Change file extension to .zip
4. Extract the content of the archive to %LOCALAPPDATA%\Loupedeck\ObsPlugin folder so that plugin DLL is in %LOCALAPPDATA%\Loupedeck\ObsPlugin\win\ObsStudioPlugin.dll
5. Start Loupedeck Service

**Comment by Spriingy** [comment]
Work like a charms with u solution ! 

Asking for a PR because i can't pull PR

Do you think is possible to add like Streamdeck the OBS Controlling media sources because i can't launch the same vidéo on differente scènes

**Comment by laperie** [comment]
> Work like a charms with u solution !
Great!

> 
> Asking for a PR because i can't pull PR
> 
> Do you think is possible to add like Streamdeck the OBS Controlling media sources because i can't launch the same vidéo on differente scènes

That's an open-source project so everything is possible :).   Appreciate if you can at least add a separate issue as a feature request, describing what you believe needs to be added.

For PR, we'll investigate the configuration of this project. There should not be any limitations in submitting a PR.

**Comment by laperie** [comment]
@Spriingy, if possible at all can you please do the following experiment: 
1. Stop Loupedeck
2. Move away the ObsStudio folder from %LOCALAPPDATA%\Loupedeck\Plugins 
3. Start Loupedeck with logging 
4. Try installing ObsStudio from Marketplace
5. Attach the logs here if it fails ---  We are still trying to figure out what caused the metadata file to disappear and having logs would help  (The logs you have attached are likely done after n-th installation attempt so there might be some residual files in Plugins\ObsStudio folder)

**Comment by danielheene** [comment]
Hey,

since the updating Loupedeck to its latest version, updating the OBS plugin fails on my machine, too. 

> @Spriingy, if possible at all can you please do the following experiment:
> 
> 1. Stop Loupedeck
> 2. Move away the ObsStudio folder from %LOCALAPPDATA%\Loupedeck\Plugins
> 3. Start Loupedeck with logging
> 4. Try installing ObsStudio from Marketplace
> 5. Attach the logs here if it fails ---  We are still trying to figure out what caused the metadata file to disappear and having logs would help  (The logs you have attached are likely done after n-th installation attempt so there might be some residual files in Plugins\ObsStudio folder)

And the previously mentioned workaround seems to be for Windows only? 
And to be honest, it doesn't feel like supporting macOS is a goal of Loupedeck.  😔

---

[loupedeckLogs.zip](https://github.com/Loupedeck-open-source/Loupedeck-ObsStudio-OpenPlugin/files/10249392/loupedeckLogs.zip)

- macOS 12.6 (21G115) 
- M1 Pro / ARM 
- Loupedeck 5.4.0.15100 
- OBS 28.1.2

**Comment by laperie** [comment]
> Hey,
> 
> since updating Loupedeck to its latest version, updating the OBS plugin fails on my machine, too.
[ ... ] 
> 
> * macOS 12.6 (21G115)
> * M1 Pro / ARM
> * Loupedeck 5.4.0.15100
> * OBS 28.1.2
---------------------
A couple of notes 
1.  Currently OBS Plugin update is not built for Mac, the Mac version should come sometime next week
2.  If on Mac OS you are getting the update notification, it's a bug -- we will look into that

**Comment by laperie** [comment]
The new versions of OBS plugin (from v5.4.2.20000 onwards)  should be working for Mac.   @danielheene please reopen the issue if that won't work for you.
